services:
  dlx-svr:
    image: hominsu/dlx-svr:latest
    container_name: dlx-svr
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "../configs:/data/conf"
    ports:
      - "3000:3000"
    networks:
      net:
        aliases:
          - dlx-svr

networks:
  net:
    driver: bridge
